"""Build the bundled Python engine as an on-disk runtime directory."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BINARIES = ROOT / "desktop" / "src-tauri" / "binaries"
DIST = ROOT / "build" / "sidecar-dist"
WORK = ROOT / "build" / "sidecar-work"


def main() -> None:
    executable_name = "engine-sidecar.exe" if sys.platform == "win32" else "engine-sidecar"
    runtime_dir = BINARIES / "engine-sidecar-runtime"

    shutil.rmtree(DIST, ignore_errors=True)
    shutil.rmtree(WORK, ignore_errors=True)
    shutil.rmtree(runtime_dir, ignore_errors=True)
    BINARIES.mkdir(parents=True, exist_ok=True)
    for old_binary in BINARIES.glob("engine-sidecar-*"):
        if old_binary.is_dir():
            shutil.rmtree(old_binary)
        else:
            old_binary.unlink()

    subprocess.run(
        [
            sys.executable,
            "-m",
            "PyInstaller",
            "--noconfirm",
            "--clean",
            "--onedir",
            "--name",
            "engine-sidecar",
            "--distpath",
            str(DIST),
            "--workpath",
            str(WORK),
            "--specpath",
            str(WORK),
            "--collect-data",
            "engine",
            str(ROOT / "packaging" / "engine_sidecar.py"),
        ],
        cwd=ROOT,
        env={**os.environ, "PYINSTALLER_CONFIG_DIR": str(WORK / "cache")},
        check=True,
    )
    source = DIST / "engine-sidecar"
    shutil.copytree(source, runtime_dir)
    destination = runtime_dir / executable_name
    destination.chmod(destination.stat().st_mode | 0o111)
    (runtime_dir / ".development-placeholder").write_text(
        "The packaged sidecar is generated by tools/build_sidecar.py.\n",
        encoding="utf-8",
    )
    print(runtime_dir)


if __name__ == "__main__":
    main()
